services:
  - type: web
    name: location-share
    env: python
    pythonVersion: 3.11.0
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --timeout 120 --keep-alive 5 --log-level debug app:app
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 1